rustls/webpki

.github/workflows/ci.yml

Goals here are:
1. Reduce the number of custom shell scripts maintained here.
2. Let developers type locally, eg,
$ cargo tarpaulin --all-features --engine llvm --out html
and get a report of uncovered lines.
Downside is that cargo-tarpaulin is pretty slow to `cargo install`.

Use ~~tarpaulin~~ llvm-cov for coverage

---

src/end_entity.rs
src/lib.rs
src/name.rs
src/name/ip_address.rs
src/name/name.rs
src/name/verify.rs
tests/integration.rs

- Mimic std names `IpAddr::V4`, `IpAddr::V6` for owned addresses, as well as `IpAddrRef::V4`, `IpAddrRef::V6` for referenced ones. Also mimic the exception name, now named `AddrParseError` instead of `InvalidIpAddressError`.
- Update copyright header on `name.rs`.
- Reduce the number of allocations on `ipv6_to_uncompressed_string` used to print IPv6 addresses in their uncompressed form.
Other minor changes.
This addresses most of the feedback provided in https://github.com/rustls/webpki/pull/5#pullrequestreview-1231025654.

IP address support: Address code review comments

---

Cargo.toml
README.md

We're starting from 0.100.0 so there is minimal future confusion with the upstream version space (currently 0.22.0).
This also adds a note to the README about the fork, and a changelog, and some badges.

Prepare README and fork versions

---

src/cert.rs
src/error.rs
tests/cert_without_extensions.rs

Allows V3 certificates without extensions (like those used by Tor) for backwards-compatibility.
This is a re-submit of @janimo's https://github.com/briansmith/webpki/pull/241 from [briansmith/webpki](https://github.com/briansmith/webpki) to the [rustls/webpki](https://github.com/rustls/webpki) fork.

Allow validating V3 certificates that have no extensions

---

README.md

I think this code has had enough use and testing to no longer call it a prototype.

Remove "very first prototype" language

---

src/subject_name/dns_name.rs
src/time.rs
tests/integration.rs
tests/name_tests.rs

Adds a `#[deprecated]` annotation. Updates tests to allow deprecated usage of existing approach and to add usage of the preferred trait.
As mentioned in the commit comment we can't outright `#[deprecate]` this one [because it's a trait impl](https://github.com/rust-lang/rust/issues/39935).
Instead, promote the deprecation note to the rustdoc comment, add a TODO to remove it outright, and switch our own tests to call `to_owned()` directly in preparation of an eventual removal. 
Resolves https://github.com/rustls/webpki/issues/47

stronger deprecations.

---

src/end_entity.rs
src/verify_cert.rs

Just a couple small fixes I noticed while studying the path building code and adjacent helpers.
Previously the rustdoc comment on `EndEntityCert.verify_is_valid_tls_client_cert` mentioned that it would
return `Error::CertNotValidForName` if the cert isn't valid for any of the given names. In reality no names are passed into this fn and it will not ever return `CertNotvalidForName`. The caller must use `EndEntityCert.verify_is_valid_for_subject_name` for this purpose.
This commit removes the erroneous mention of name validation from `verify_is_valid_tls_client_cert`.
Previously the `check_eku` helper described details of RFC 5280 deviations that no longer match the implementation. In particular, the `id-Netscape-stepUp` EKU workaround was removed (see …

cert verification rustdoc comment touchups.

---

src/error.rs
src/subject_name/dns_name.rs
src/subject_name/verify.rs

Previously the `presented_id_matches_constraint` and `presented_id_matches_reference_id` functions used by `verify_cert_dns_name` would return an `Option<bool>`, with the `None` case translated into `Error::BadDer`. This makes it difficult for downstream users to know that the encoding error was specific to an invalid presented DNS ID, or a DNS name constraint.
This commit introduces two new error variants: `MalformedDnsIdentifier` and `MalformedNameConstraint`. The `presented_id_matches_constraint` and `presented_id_matches_reference_id` functions are changed to return `Result<bool, Error>` using the new error types. This better matches the `presented_id_matches_reference_id` and `presented_id_matches_constraint` impls. used for `IpAddress` subjects that already return `Result<bool, …

subject_name: more specific errs for invalid names.

---

.github/workflows/ci.yml
Cargo.toml
src/end_entity.rs
src/subject_name/dns_name.rs
src/time.rs
tests/cert_v1_unsupported.rs
tests/cert_without_extensions.rs
tests/integration.rs
tests/name_constraints.rs

The MSRV was extremely conservative before, much more so than what we have for rustls 1.57.0. I don't think there's much motivation for keeping that, since as far as I know our main (only?) interest is maintaining rustls-webpki for use in rustls (it's right there in the name). Pull it up to 1.57 (which is still pretty conservative!) now that there is something of [a reason](https://github.com/rustls/webpki/pull/44#discussion_r1191011437) to move forward.

Update MSRV to 1.57 to match rustls

---

src/cert.rs

Revocation checking based on certificate revocation lists (CRLs) is done by checking a validated CRL for an end-entity certificate's serial number. In preparation for implementing this we must retain certificate serial numbers when parsing, instead of discarding after reading.
We don't attempt to decode the raw serial number as a big integer since for the purpose of revocation checking we can match the ASN.1 encoded form without further processing.
Trust anchors will not be checked for revocation using CRLs so we do not augment the `TrustAnchor` representation and instead continue to discard the serial number when parsing TAs.
Relates to https://github.com/rustls/webpki/issues/56

cert: retain parsed Cert serial number.

---

.github/workflows/testgen.yml
tests/generate.py

This branch follows https://github.com/rustls/webpki/pull/64 and introduces a few more helpful generalizations/cleanups that I made while writing CRL focused test cases.
Some highlights:
* Lifts out common helper functions for generating end entity and CA certificates that can be shared by several of the more specific test case generators.
* Tidies up some duplicated path manipulation/strings.
* Adds simple command line flags to allow control over which test cases are generated and whether the `cargo fmt` and `cargo test` invocations are run post-generation.
* Generalizes the CA certificate generation to allow generating intermediate certificates in addition to self-signed roots, and to allow optionally specifying key usage.
These changes do not affect the generated test cases so I …

tests: further cleanup/generalization.

---

src/subject_name/ip_address.rs
src/subject_name/verify.rs

Previously the ip address module's `presented_id_matches_reference_id` function returned `Result<bool, Error>`, similar to the DNS subject name function of the same name.
In the case of the IP address implementation there is no codepath that returns an error. The lengths of the inputs are checked ahead of time, and the DER reads are infallible for the byte-for-byte compare. All of our unit tests also expect a true/false return, not an error.
With the above in mind this commit changes the
`presented_id_matches_reference_id` return type to `bool` and updates the call-sites and unit tests accordingly.

subject_name: rm unused err return for IP subj. cmp.

---

src/crl.rs
tests/crl_tests.rs

We don't want to add `untrusted` to webpki's public API, but several fields of the `CertificateRevocationList` type did this accidentally when it was added in https://github.com/rustls/webpki/pull/44.
This branch makes the `untrusted::Input` fields crate-private and adds public methods that can return `&[u8]` versions of these fields for external usage.
Along the way I also deleted the `CertificateRevocationLists` type - we didn't export that from `lib.rs`. I added this type before landing on the `CrlProvider` trait implemented in [a separate branch](https://github.com/rustls/webpki/pull/66). With that approach there's no need for a list-of-CRLs type. This also side-steps concerns about the best data structure to use: each `CrlProvider` implementation can choose their own approach.

crl: remove exports of `untrusted::Input`.

---

src/cert.rs
src/crl.rs
src/der.rs
src/error.rs
src/signed_data.rs

This branch updates the Webpki `der` module to offer some function variants that allow reading a DER encoded tag and value where the value's length can be expressed as a long-form length of up to four bytes. 
To do this we have to lift the `ring::io::der` module's `read_tag_and_get_value` function into `webpki`, since it is hardcoded to support long-form lengths no longer than two bytes and the upstream is not responsive to patches at this time. Once the function is within the `webpki` code and can be modified we tweak it to support lengths up to five bytes, and to allow the caller to specify a maximum `usize` to read. 
The primary use-case for larger values is for supporting using `parse_signed_data` on large CRLs. To enable this the `parse_signed_data` function is updated to accept a …

der/signed_data: introduce support for larger DER values.

---

.github/workflows/ci.yml
tests/client_auth_revocation.rs

Quick branch to make CI a little bit more strict with respect to warnings in test code, and to fix some test failures.
We had a small merge snafu where the `try_from` trait was removed in one branch, but another branch had landed first that added more tests using it. This commit fixes those tests to use `from_der` instead of the missing `try_from` fn. 
I'll start a discussion about repo settings we can explore to prevent this in the future.
The `ALL_SIGALGS` and `check_cert` portions of `client_auth_revocation.rs` are unused when testing without the alloc
feature.
Looking at this more carefully I _think_ the only reason a bunch of this test code is config-gated on `alloc` is that I used RSA keys for the test issuers/keypairs. In a follow-up branch I'll look at making these tests work …

ci: forbid warnings from cargo test

---

src/crl.rs
src/verify_cert.rs

The `RevocationReaason` enum should use explicit c-style enum values in order to make sure that the values line up with the RFC defined codes. In particular, since 7 is not used we want to make sure that `RemoveFromCrl` is 8.
_(Also removes a stale `todo` about revocation support in `verify_cert.rs)_

crl: explicitly number RevocationReason codes.

---

src/subject_name/dns_name.rs
src/subject_name/verify.rs
src/time.rs
tests/integration.rs
tests/name_tests.rs

In preparation for considering a major release this branch resolves a few items we had flagged as breaking changes.
This commit replaces the `DnsNameRef` type's `AsRef<[u8]>` implementation with a `AsRef<str>` replacement.
We know the contents of a `DnsNameRef` are valid UTF-8 and it's trivial to go from `&str` to `&[u8]` making the `AsRef<str>` option a more capable API.
Resolves https://github.com/rustls/webpki/issues/45
This trait was marked as deprecated in a comment (it couldn't be hard-deprecated as a trait impl), let's remove it before the next breaking release.
This commit removes the manually implemented `try_from` on `Time` that was marked as deprecated. Users should prefer `TryFrom::try_from`. 
Similarly, we update the `TryFrom` impl for `Time` to return …

Small breaking API changes removing deprecated items.

---

.github/workflows/testgen.yml
tests/generate.py

Typically when we make changes to generated tests we don't need to regenerate the binary certificates, private keys, and signature messages. Doing so is non-deterministic and muddies our diffs with lots of unrelated changes.
This commit improves the situation by defaulting to not overwriting existing keys/certs when running `generate.py` unless `--force` is provided. We will still do a little bit of unnecessary work generating keypairs/certs that won't be serialized but it avoids a more substantial rework of the generation code while still achieving our goal of avoiding
extra noise.
This way we can be sure that the code to generate fresh certs/keys for our generated test cases work as expected.

tests: avoid messy testfile churn from generate.py

---

.github/workflows/testgen.yml

Previously we ran `generate.py` with `--force` and default arguments in CI. This is suboptimal in that it silently overwrites test files without anyone looking at them and means we're testing something other than what's checked in to git.
This commit takes a different approach and removes the `--force` arg. We also skip running `cargo test` by providing `--no-test` and instead just verify that running generate produces no diff from what's been checked in-tree and tested in the other CI task.

ci: enforce generate.py produces no diff.

---

src/lib.rs

The Rustls fork of webpki doesn't host rustdocs somewhere that would require a `html_root_url` doc attribute override. This commit removes the stale instance from the upstream crate this one was forked from.

lib: remove stale html_root_url doc attribute.

---

src/crl.rs
src/der.rs
src/verify_cert.rs

Lifting the actionable parts out of https://github.com/rustls/webpki/pull/92
These were meant to be removed in earlier work and were overlooked.
Previously (https://github.com/rustls/webpki/pull/73) we updated the `der` module to have methods that allow specifying an explicit size limit so that the `crl` module could opt-in to reading DER values larger than the implicit maximum supported by *ring*. 
Unfortunately this update wasn't quite complete: we need a `der::nested_limited` version of `der::nested` to read the nested sequence with the large signed data we pass to `signed_data::parse_signed_data` or we'll run into the implicit limit before we get to the parsing that supports a larger data size.
Similarly when reading the `SEQUENCE` that holds all of the revoked certificates we need to …

der/crl: fix support for large CRL DER.

---

.github/workflows/ci.yml
.github/workflows/testgen.yml

This commit adds `merge_group` to our CI task `on` triggers in preparation for enabling the merge queue feature.
Per the [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
> You must use the merge_group event to trigger your GitHub Actions
> workflow when a pull request is added to a merge queue.
>
> Note: If your repository uses GitHub Actions to perform required
> checks on pull requests in your repository, you need to update the
> workflows to include the merge_group event as an additional trigger.
> Otherwise, status checks will not be triggered when you add a pull
> request to a merge queue. The merge will fail as the required status
> check will not be reported. The …

ci: add merge_group trigger to ci tasks.

---

Cargo.toml

Don't distribute 3-clause BSD test artifacts

---

SECURITY.md

Over in the main Rustls repo we updated the `SECURITY.md` policy on supported versions to give more detail (https://github.com/rustls/rustls/pull/1315).
This commit synchronizes the webpki `SECURITY.md` to match.

docs: sync SECURITY.md backport policy w/ Rustls.

---

.github/workflows/ci.yml

(I have added a github actions secret named `CODECOV_UPLOAD_TOKEN` which is the "Repository upload token" from codecov.io.) For background, see: https://github.com/codecov/codecov-action/issues/837#issuecomment-1453877750

codecov: use upload token to improve reliability

---

.github/workflows/ci.yml
Cargo.toml
src/der.rs

This commit introduces a CI target that uses [cross](https://github.com/cross-rs/cross) to cross-compile for a ` i686-unknown-linux-gnu` target to ensure we maintain 32bit arch compatibility. Unfortunately I don't believe GitHub actions has a native 32bit runner so cross-compilation is our best bet.
Before applying the subsequent fix commit [this task fails](https://github.com/cpu/webpki/actions/runs/5467843860/jobs/9954676804) with the error reported in #112:
```
Compiling rustls-webpki v0.101.0 (/home/runner/work/webpki/webpki)
error[E0080]: evaluation of constant value failed
--> src/der.rs:246:45
|
246 | const LONG_FORM_LEN_FOUR_BYTES_MAX: usize = (1 << (8 * 4)) - 1;
|                                             ^^^^^^^^^^^^^^ attempt to shift left by `32_i32`, which would overflow …
```

fix 32 bit support, add i686-unknown-linux-gnu CI target

---

README.md

v0.101.1 release prep

---

.gitignore
Cargo.toml
benches/benchmark.rs
deny.toml

This branch adds two kinds of CRL benchmark tests:
1. Parsing benchmarks, testing how long it takes to use `BorrowedCertRevocationList::from_der`, as well as how long it takes to do the same converting to the `OwnedCertRevocationList` representation that allocates.
2. Searching benchmarks, testing how long it takes to search an already parsed CRL for a serial number that doesn't appear in the CRL. This is done for both the borrowed and owned representations.
In both cases we add benchmarks that use three sizes of CRLs:
1. a small CRL (2,000 serials, ~72kb)
2. a medium CRL (600,000 serials, ~22mb)
3. a large CRL (1,500,000 serials, ~50mb)
Since large test files aren't suitable for inclusion in git, these CRLs are generated on first benchmark run using `rcgen`. We use a Cargo patch to use …

benches: CRL parsing/searching benchmarks.

---

Cargo.toml

The Rustls project is the primary motivator for this fork of webpki, and it always uses webpki _with_ alloc. It doesn't seem likely that we'll want to make alloc non-default in the near future, let alone in a next release.

cargo: remove TODO about non-default alloc.

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/lib.rs

This matches the main Rustls project MSRV (https://github.com/rustls/rustls/pull/1312).
Previously we had to break out some `pub use` statements individually to work around Rust 1.57 clippy false positives for `unreachable_pub`.
Having bumped the MSRV to 1.60 we can remove this workaround.

project: increase MSRV, 1.57 -> 1.60

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/testgen.yml

In https://github.com/rustls/webpki/pull/115 it was [pointed out](https://github.com/rustls/webpki/pull/115#discussion_r1253867792) that the webpki CI wasn't very consistent with the Rustls repo. In particular the whitespace style differed, and steps weren't being annotated with `name`s.
This branch does a quick standardization pass, and also adds a new `cargo-semver-check` step, tightens up the `cargo doc` step to forbid warnings, adds a cron schedule, and adds a dependabot config.
Probably easiest to review commit-by-commit.

ci: match Rustls style, add cargo-semver-checks, dependabot

---

.github/workflows/ci.yml
Cargo.toml
src/crl.rs
src/end_entity.rs
src/error.rs
src/lib.rs
src/signed_data.rs
src/subject_name/dns_name.rs
src/subject_name/ip_address.rs
src/time.rs

This branch replaces the convention of calling out required features manually in rustdoc comments with application of cfg attrs that can do the same in a way that rustdoc can pick up and render as a more legible warning.
Resolves https://github.com/rustls/webpki/issues/122

 docs: add attributes indicating req'd features.

---

Cargo.toml
benches/benchmark.rs
src/signed_data.rs
tests/better_tls.rs

Replacement for https://github.com/rustls/webpki/pull/124 that addresses clippy warnings and deprecated base64 fn usage.
We don't want octal constants here, they're decimal.
Self explanatory.
Self explanatory.
This commit updates the `base64` dev-dependency.
Since the old style `base64::decode` is now marked deprecated we also replace these invocations with the engine-based alternatives.

clippy fixes, base64 dev-dep 0.13 -> 0.21.

---

src/crl.rs
src/signed_data.rs

This branch adds derived `Debug` traits to:
* `BorrowedCertRevocationList`
* `BorrowedRevokedCert`
* `RevokedCerts`
* `SignedData`
* `OwnedCertRevocationList`
* `OwnedRevokedCert`
* `OwnedSignedData`
It additionally adds derived `Clone` traits to:
* `OwnedCertRevocationList`
* `OwnedRevokedCert`
* `OwnedSignedData`

crl/signed_data: add Debug and Clone as sensible.

---

src/cert.rs
src/crl.rs
src/end_entity.rs
src/signed_data.rs
src/subject_name/verify.rs
src/trust_anchor.rs
src/verify_cert.rs

Triggered by reviewing https://github.com/rustls/webpki/pull/127/commits/71cfc964c0245b7252dbc3aeb79ec7c12337e642 -- sorry if this ends up inducing extra rebase work!

Turn free-standing construction functions into associated methods

---

Cargo.toml
README.md

- MSRV increased to Rust 1.60.
- Correct bug in CRL processing where certificates with certain forms of serial number were not revocable.
- Added API for verifying certificate chain with a custom EKU.
- `TlsServerTrustAnchors`, `TlsClientTrustAnchors`, `verify_is_valid_tls_server_cert` and `verify_is_valid_tls_client_cert` are deprecated: use `verify_for_usage` with `KeyUsage::server_auth()` or `KeyUsage::client_auth()` instead.

Prepare release 0.101.2

---

src/cert.rs
src/crl.rs
src/der.rs
src/signed_data.rs
src/subject_name/verify.rs
src/verify_cert.rs
src/x509.rs

Right now this is only a little bit more concise but I feel like it might help structure things going forward?
Needs a thorough audit for the correctness of consuming entire DER sequences, not sure we're entirely consistent (and have good coverage of) the `read_all()` aspect of things. (But I think this could help get that right in the future?)

Implement FromDer trait and DerIterator type

---

src/subject_name/verify.rs

This makes the abstractions a lot more intuitive/idiomatic in my opinion.
I think it has the potential to bring `list_cert_dns_names()` out of the `alloc` domain (see #46), but that would be at the cost of making it yield an `impl Iterator<Item = Result<GeneralName<'_>, Error>>` rather than a `Result<impl Iterator<Item = GeneralName<'_>>, Error>` which might be undesirable?

Name iterator

---

.github/workflows/ci.yml
Cargo.toml
src/crl.rs
src/signed_data.rs

this PR
- makes the `alloc` feature not pull in the optional `ring` dependency
- fixes `cargo build --no-default-features --features alloc`
- adds a CI check to prevent no-std support breaking in the future
fixes #143 
fixes #144

fix no-std support

---

src/cert.rs
src/crl.rs
src/der.rs
src/end_entity.rs
src/error.rs
src/lib.rs
src/ring_algs.rs
src/signed_data.rs
src/subject_name/verify.rs
src/time.rs
src/trust_anchor.rs
src/verify_cert.rs
src/x509.rs
tests/crl_tests.rs

Now that we no longer depend on generic *ring* things, there is a bunch of stuff we can do to simplify DER handling.

Refactor DER parsing

---

Cargo.toml
src/end_entity.rs
src/trust_anchor.rs

This branch (_that I should have named more generally, in retrospect_) targets a base of `rel-0.101`, created from the v0.101.2 tag.
The deprecations mentioned in https://github.com/rustls/webpki/issues/148 were in the released 0.101.2, but `main` has already removed the deprecated elements. In order to improve the deprecation notes we'll need to start a release branch. I've gone ahead and done that roughly following the [rustls guidance](https://github.com/rustls/rustls/blob/main/RELEASING.md#maintenance-point-releases).
- `TlsServerTrustAnchors`, `TlsClientTrustAnchors`, `verify_is_valid_tls_server_cert` and `verify_is_valid_tls_client_cert` deprecation notes improved.
In 0.101.2 we deprecated the `TlsServerTrustAnchors` and `TlsClientTrustAnchors` types along with the …

0.101.3 release prep

---

src/crl.rs
src/end_entity.rs
src/error.rs
src/lib.rs
src/ring_algs.rs
src/signed_data.rs
src/subject_name/dns_name.rs
src/subject_name/ip_address.rs
src/time.rs

Also remove now-duplicated comments about what features an item requires.

Use doc_auto_cfg and remove manual doc(cfg()) gates

---

src/error.rs
src/verify_cert.rs

Pathbuilding complexity can be quadratic, particularly when the set of intermediates all have subjects matching a trust anchor. In these cases we need to bound the number of expensive signature validation operations that are performed to avoid a DoS on CPU usage.
This commit implements a simple maximum signature check limit inspired by [the approach taken in the Golang x509 package](https://github.com/golang/go/commit/df523969435b8945d939c7e2a849b50910ef4c25). No more than 100 signatures will be evaluated while pathbuilding. This limit works in practice for Go when processing real world certificate chains and so should be appropriate for our use case as well.
Without the limit in place, the `test_too_many_signatures` unit test has very long runtime and quickly pegs my local CPU. With the …

verify_cert: enforce maximum number of signatures.

---

Cargo.toml
src/error.rs
src/verify_cert.rs

This branch targets a base of `rel-0.101` to prepare a point release in the v0.101.x series.
- certificate path building and verification is now capped at 100 signature validation operations to avoid the risk of CPU usage denial-of-service attack when validating crafted certificate chains producing quadratic runtime. This risk affected both clients, as well as servers that verified client certificates.
Pathbuilding complexity can be quadratic, particularly when the set of intermediates all have subjects matching a trust anchor. In these cases we need to bound the number of expensive signature validation operations that are performed to avoid a DoS on CPU usage.
This commit implements a simple maximum signature check limit inspired by the approach taken in the Golang x509 package. No more …

v0.101.4 prep

---

.github/workflows/ci.yml
Cargo.toml
src/end_entity.rs
src/error.rs
src/verify_cert.rs

This branch targets a base of `rel-0.100` to prepare a point release in the v0.100.x series.
- certificate path building and verification is now capped at 100 signature validation operations to avoid the risk of CPU usage denial-of-service attack when validating crafted certificate chains producing quadratic runtime. This risk affected both clients, as well as servers that verified client certificates.
Pathbuilding complexity can be quadratic, particularly when the set of intermediates all have subjects matching a trust anchor. In these cases we need to bound the number of expensive signature validation operations that are performed to avoid a DoS on CPU usage.
This commit implements a simple maximum signature check limit inspired by the approach taken in the Golang x509 package. No more …

v0.100.2 prep

---

.github/workflows/ci.yml
src/x509.rs

Inspired by @ctz and https://github.com/rustls/rustls/pull/1419

Enable warnings for `cargo doc` comments on private items

---

Cargo.toml
src/end_entity.rs
src/lib.rs
src/trust_anchor.rs
src/verify_cert.rs
tests/better_tls.rs
tests/cert_v1_unsupported.rs
tests/cert_without_extensions.rs
tests/client_auth.rs
tests/client_auth_revocation.rs
tests/custom_ekus.rs
tests/integration.rs
tests/signatures.rs
tests/tls_server_certs.rs

See https://github.com/rustls/pki-types/pull/1 for more context.
The `cargo package` and `cargo deny` failures in CI are expected given the temporary introduction of a git dependency. I'd expect we can release a pki-types 1.0.0-alpha.1 before we merge this, but want to get PRs to a bunch of other crates in place (and, ideally, reviewed) before we do that.

Switch to using the pki-types crate

---

Cargo.toml

This helps further downstream testing of the pki-types switch, avoiding the need to rely on git dependencies.

Bump version to alpha.1 with pki-types

---

src/error.rs
src/verify_cert.rs

This is intended to be complementary to #160 and addresses briansmith/webpki#276 in the same manner as NSS libmozpkix.

Further limits on expensive path building

---

src/crl.rs
src/ring_algs.rs
src/signed_data.rs
src/verify_cert.rs

Two minor style nits and an attempt at better forcing consumption of signature verification budget.
This is basically follow-up from #163.

Budget tweaks

---

src/subject_name/mod.rs

Noticed this while backporting various changes for #170.
My kingdom for a `clippy` lint that can tell when `unused_imports` allows aren't needed anymore 😩

subject_name: fix stale unused_imports allow.

---

Cargo.toml
src/end_entity.rs
src/error.rs
src/signed_data.rs
src/subject_name/verify.rs
src/verify_cert.rs

This branch targets a base of rel-0.100 to prepare a point release in the v0.100.x series.
It brings in:
* https://github.com/rustls/webpki/pull/163
* https://github.com/rustls/webpki/pull/164
* https://github.com/rustls/webpki/pull/165
* https://github.com/rustls/webpki/pull/168
Unlike https://github.com/rustls/webpki/pull/170 we don't bring in clippy fixes (they applied to CRL code that isn't present in this branch), and we don't bring in the subject common name handling changes (since the problematic parsing isn't exposed to users via the name iteration code that's only in 0.101+ it didn't seem worthwhile).
I won't call out each individual commit this time since there are many :-) In terms of required adjustments for backporting there were more substantial changes in this branch than …

v0.100.3 preparation

---

.github/workflows/ci.yml
src/verify_cert.rs
tests/better_tls.rs

Recently our unit test runtime has been bogging down. Three tests in particular were slow relative to the rest: `test_too_many_path_calls` from `verify_cert.rs`, and the path building and name constraint test suites from the [bettertls](https://github.com/Netflix/bettertls) based integration test. Our entire project test suite minus those three tests completes in <0.5s.  Running `test_too_many_path_calls` alone takes ~3s, and the better tls suite was ~8s.
This branch does a few things to remedy this:
* It makes `test_too_many_path_calls` run faster by setting a lower `build_chain_calls` budget.
* It makes the better tls test suite opt-in by ignoring both tests by default.
* It updates CI to run ignored tests.
* It adds a `cargo hack` feature powerset test to CI.
This should help keep …

tests: local test speed optimizations, add cargo hack feature powerset

---

CONTRIBUTING.md

Rather than maintain the same content in two places let's just point webpki contributors to the Rustls `CONTRIBUTING.md`.

docs: add CONTRIBUTING.md, ref'ing Rustls CONTRIBUTING

---

src/end_entity.rs
src/test_utils.rs
src/verify_cert.rs

Previously (https://github.com/rustls/webpki/pull/168) we fixed the test case  that used the `build_degenerate_chain` helper to test the build chain call budget (introduced in https://github.com/rustls/webpki/pull/163) by artificially inflating the signature validation limit. This was crummy for a few reasons:
1. It required faking the budget, both to increase the signature validation limit (to avoid hitting that limit first) and to decrease the build chain call budget (to avoid the test taking ~6s to run).
2. It didn't demonstrate very well why two separate limits are required, as it gave the sense under normal circumstances the signature validation limit would reject the pathological chain.
This branch reworks `build_degenerate_chain` so that it can reproduce a pathological chain that …

properly test build chain call budget

---

src/cert.rs
src/end_entity.rs
src/lib.rs
src/signed_data.rs
src/subject_name/dns_name.rs
src/subject_name/mod.rs
src/subject_name/verify.rs
tests/integration.rs

This branch reworks the `EndEntityCert`'s `dns_names` helper. Principally it:
* Simplifies the unit testing, and cleans up some misc nits.
* Reworks `dns_names` and the corresponding `subject_name::list_cert_dns_names` fns to be infallible, this better matches how we're ignoring invalid DNS names when validating a subject name since #69.
* Removes the `alloc` requirement for the `dns_names` fn.
* Reworks the name ref types to use `as_str` instead of a `From` impl
* Removes the `GeneralDnsNameRef` type (with the potential to restore as future work c.f. #183)
* Moves the `subject_name::list_cert_dns_names` free-standing fn to be associated with `Cert` and named `valid_dns_names`.
Resolves https://github.com/rustls/webpki/issues/46, replaces https://github.com/rustls/webpki/pull/50

rework `dns_names` helper, remove alloc req.

---

src/cert.rs
src/end_entity.rs
src/subject_name/verify.rs
src/verify_cert.rs
tests/integration.rs

Avoids duplication and seems generally right. I think this would also make sense in the context of #174.

Let EndEntityCert deref to Cert

---

Cargo.toml
src/crl.rs
src/verify_cert.rs

This branch targets the `rel-0.101` release branch to make a point release fixing https://github.com/rustls/webpki/issues/185.
* The `CertificateRevocationList` trait's `verify_signature` `Budget` argument was removed. This was a semver incompatible change mistakenly introduced in v0.101.5.

v0.101.6 release prep

---

src/end_entity.rs
src/subject_name/dns_name.rs
src/subject_name/ip_address.rs
src/subject_name/mod.rs
src/subject_name/verify.rs

Moves code around to reduce coupling and introduce clearer abstractions. Preamble for work on #183.

Refactor name verification flow

---

Cargo.toml
benches/benchmark.rs

The `rcgen` crate has cut a 0.11.2 release that includes the CRL functionality we were using a Cargo patch to depend on previously. This commit removes the patch, fixes a breakage in the CRL benchmark, and updates the `Cargo.toml` file.
We temporarily include the "pem" feature to avoid a build breakage introduced in 0.11.2 yet to be fixed upstream (https://github.com/rustls/rcgen/issues/161).

Cargo: remove rcgen git patch

---

src/crl/mod.rs
src/crl/types.rs
src/verify_cert.rs

The `Budget` type is a crate-internal detail that shouldn't be exposed outside of the crate. It only makes sense in the context of path path building.
This commit removes the `Budget` argument from the public `CertRevocationList` trait's `verify_signature` fn.
See https://github.com/rustls/webpki/pull/186 for a discussion of rejected alternative solutions.

crl: rm Budget from verify_signature fn

---

Cargo.toml

Rcgen 0.11.3 has been released and fixed the semver breakage that required temporarily using the `pem` feature.

Cargo: restore rcgen w/ no-default-features

---

src/verify_cert.rs

Restores test from #191 that was dropped from https://github.com/rustls/webpki/pull/174 in a rebase.

verify_cert: add test for rejecting candidate path

---

.github/workflows/ci.yml
Cargo.toml
src/crl/types.rs
src/der.rs
src/error.rs

Like https://github.com/rustls/rustls/pull/1535, this branch brings the [cargo-check-external-types](https://github.com/awslabs/cargo-check-external-types) tool to the webpki repo. This will help us catch unintended leaking of types from dependencies into the public API. One such occurrence is caught by the tool and fixed alongside adding it to CI.

Use cargo-check-external-types to control type leakage in public API 

---

.github/workflows/ci.yml
Cargo.toml
benches/benchmark.rs
src/cert.rs
src/crl.rs
src/der.rs
src/lib.rs
src/signed_data.rs
src/verify_cert.rs

This branch targets the `rel-0.101` release branch to make a point release to upgrade to *ring* 0.17. This will unblock a Rustls 0.21 point release that does the same.
This involves bringing the work from https://github.com/rustls/webpki/pull/193 onto the rel-0.101 branch. I didn't cherry-pick the commits directly because the restructuring of the modules in `main` made it more challenging to resolve conflicts than to re-implement the changes wholesale.
The `rcgen` update (from https://github.com/rustls/webpki/pull/189 and https://github.com/rustls/webpki/pull/195) isn't mentioned in the proposed release notes since it's a dev dependency. We also don't typically mention MSRV updates, so its omitted as well.
* Upgrades `*ring*` to 0.17, and `untrusted` to 0.9. _Note: since `unstrusted` …

v0.101.7 preparation

---

src/trust_anchor.rs

Since extracting the `PathNode` from `Cert` (https://github.com/rustls/webpki/pull/173) the `XXX` comment about using `EndEntityOrCA::EndEntity` when extracting a trust anchor from `CertificateDer` is no longer accurate. This commit deletes it.

trust_anchor: fix stale note about EndEntityOrCA

---

src/lib.rs
src/trust_anchor.rs
src/verify_cert.rs
tests/better_tls.rs
tests/client_auth.rs
tests/client_auth_revocation.rs
tests/custom_ekus.rs
tests/integration.rs
tests/tls_server_certs.rs

This function has caused some confusion w.r.t self-signed end-entity certificates and their support within rustls/webpki (see https://github.com/rustls/webpki/issues/200, https://github.com/briansmith/webpki/issues/294). This branch takes two actions to try and help this situation:
1. It renames `extract_trust_anchor` to `anchor_from_trusted_cert` to emphasize that the input **must** be prevalidated out-of-band as suitable to use as a trust anchor.
2. It adds more detail to the rustdoc comment for the function, in particular emphasizing why no additional validations are performed. We also emphasize that this function is intended as a helper for users constructing trust anchor stores out of existing trust anchor stores that use an X.509 certificate representation, and that it is not …

trust_anchor: clarify and rename extract_trust_anchor

---

src/lib.rs

From discord:
> VerifiedPath being private is just an oversight, we’ll have to fix that

verify_cert: re-export VerifiedPath

---

Cargo.toml
src/aws_lc_rs_algs.rs
src/ring_algs.rs

The `SignatureVerificationAlgorithm` in pki-types was changed to have a `Debug` bound (https://github.com/rustls/pki-types/pull/13), so these type needs to be `Debug` to implement the trait.

 derive Debug for RingAlgorithm, AwsLcRsAlgorithm

---

src/cert.rs

Scheduled CI tasks [started failing](https://github.com/cpu/webpki/actions/runs/7350078635/job/20030735305) yesterday with the update to the just-released Rust 1.75 from a `clippy` finding:
```
error: accessing first element with `crl_distribution_points.get(0)`
--> src/cert.rs:620:13
|
620 | /             crl_distribution_points
621 | |                 .get(0)
| |_______________________^ help: try: `crl_distribution_points.first()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#get_first
= note: `-D clippy::get-first` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::get_first)]`
```

cert: fix clippy get_first finding

---

Cargo.toml

Draft release notes:
* **Added `webpki::aws_lc_rs::ECDSA_P521_SHA512`**: support for P521-SHA512 signature verification.

Prepare 0.102.1

---

src/cert.rs
src/crl/types.rs
src/subject_name/verify.rs
src/x509.rs

CI started failing the nightly clippy task ([example](https://github.com/rustls/webpki/actions/runs/7451466705/job/20272649231)) ~yesterday from a couple enum variants where we never accessed the inner fields.
This branch fixes both findings by removing the unused `untrusted::Input` inner fields.

small nightly clippy fixes

---

Cargo.toml

The `aws-lc-rs` crate [defaults to enabling the `ring-io` and `ring-sig-verify` features](https://github.com/aws/aws-lc-rs/blob/067c9486eb117c67a9da977256f1a99bac11bfae/aws-lc-rs/Cargo.toml#L31), but we use neither in this crate. Avoiding these features is beneficial because it prevents the inclusion of a second copy of `untrusted` in the dependency tree.
You can see the presence of the extra `untrusted 0.7.1` in `cargo tree --no-default-features --features=aws_lc_rs` before/after this change:
<details>
<summary>Cargo tree output from `main` prior to this change:</summary>
```
rustls-webpki v0.102.1 (/home/daniel/Code/Rust/webpki)
├── aws-lc-rs v1.6.1
│   ├── aws-lc-sys v0.13.0
│   │   ├── libc v0.2.150
│   │   └── paste v1.0.14 (proc-macro)
│   │   [build-dependencies]
│   │   ├── cmake …
```

Cargo: avoid unused aws-lc-rs default features

---

src/verify_cert.rs
tests/custom_ekus.rs

I noticed there isn't currently a pub function to use `ExtendedKeyUsage::RequiredIfPresent`. Unsure if there was a reason for this, or whether it was just missed?

Allow "required if present" EKUs

---

.github/workflows/ci.yml

- moves from the per-repo `CODECOV_UPLOAD_TOKEN` secret (which I'll delete shortly) to the per-org one
- removes verbose flag
- avoid failing build if upload fails

Synchronise codecov action settings with rustls

---

.github/workflows/ci.yml

Fixes [CI failures](https://github.com/rustls/webpki/actions/runs/7920411536/job/21623391421) for the associated task.

ci: sync nightly for check-external-types

---

src/alg_tests.rs
src/cert.rs
src/crl/mod.rs
src/crl/types.rs
src/der.rs
src/end_entity.rs
src/lib.rs
src/test_utils.rs
src/verify_cert.rs

This fixes compilation with nightly, which just got better at detecting redundant imports: https://github.com/rust-lang/rust/pull/117772
Mostly from @cpu/cpu-fix-nightly-clippy

Fix nightly compilation

---

Cargo.lock
Cargo.toml
benches/benchmark.rs
src/end_entity.rs
src/test_utils.rs
src/verify_cert.rs

* updates rcgen dev dependency to 0.13
* fixes breaking upstream changes
* also fixes an unrelated nightly clippy err in a separate commit

deps: rcgen 0.12 -> 0.13

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml

Replaces https://github.com/rustls/webpki/pull/246  A few additional changes are required above what was in #246:
We're seeing more of our deps move to this MSRV or higher (in this case, a transitive dep on `jobserver`) and it's shipped in Debian stable. Time to move our MSRV to 1.63.
Changing the runner image to `ubuntu-latest` takes a Ubuntu 22.04 image that includes GCC 11. This is notable because the latest [aws-lc-rs build script bails](https://github.com/aws/aws-lc-rs/blob/575f7d0656250e5302f8a9ce2ae34b3d098799b2/aws-lc-sys/builder/cc_builder.rs#L202-L260) when compiled with a GCC version affected by [a nasty `memcpy` bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189). The 20.04 image uses GCC 9 and _is_ affected.
We prefer `ubuntu-latest` in our other repositories so this …

v0.102.3, bump aws-lc-rs from 1.6.4 to 1.7.0, MSRV 1.63

---

benches/benchmark.rs

The Rust 1.80 release [broke the clippy task](https://github.com/rustls/webpki/actions/runs/8928478989) in CI with clippy findings of the form:
```
warning: current MSRV (Minimum Supported Rust Version) is `1.63.0` but this item is stable since `1.66.0`
--> benches/benchmark.rs:153:15
|
153 |     c.iter(|| black_box(assert!(matches!(crl.find_serial(FAKE_SERIAL), Ok(None)))));
|               ^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
= note: `#[warn(clippy::incompatible_msrv)]` on by default
```
This commit ignores these findings under `benches/benchmark.rs`. We don't offer an MSRV for dev-only benchmarks

benches: ignore clippy::incompatible_msrv

---

Cargo.lock
Cargo.toml
src/cert.rs
src/der.rs

Using types from https://github.com/rustls/pki-types/pull/47, this PR adds the following methods for a `cert::Cert`'s `SubjectPublicKeyInfo`:
* `pub fn subject_public_key_info(&self) -> SubjectPublicKeyInfo`
* `pub(crate) fn subject_public_key_info_contents(&self) -> &[u8]`
As `cert::Cert`'s internal representation of a `SubjectPublicKeyInfo` (`Cert::spki`) lacks the ASN.1 SEQUENCE bytes to make it a proper RFC 5280 `SubjectPublicKeyInfo`, we need to sneakily add them back when someone calls `subject_public_key_info(&self)`. I accomplished this with the addition of `der::asn1_wrap` which I mercilessly lifted from [rustls::x509::asn1_wrap](https://github.com/rustls/rustls/blob/69b5d2374eccdc4093967a188dff9a62e0c8d884/rustls/src/x509.rs#L5-L34). Not completely mercilessly, though—I did make …

Add SubjectPublicKeyInfo methods for cert::Cert

---

Cargo.lock
Cargo.toml

* `RevocationOptionsBuilder` now offers a `with_expiration_policy()` fn for setting an `ExpirationPolicy` that will be used to determine how to handle CRLs that have a `NextUpdate` value in the past. The default behaviour is to ignore the `NextUpdate`. Users wishing to use a stricter policy can do so by specifying `ExpirationPolicy::Enforce`. Revocation checking against an expired CRL will then produce an `Error::CrlExpired` error.
* `EndEntityCert` now offers a `subject_public_key_info()` fn for accessing the RFC 5280 `pki_types::SubjectPublicKeyInfoDer`.

Cargo: v0.102.3 -> v0.102.4

---

.github/workflows/ci.yml

The upstream project cut a [0.1.12 release](https://github.com/awslabs/cargo-check-external-types/releases/tag/v0.1.12) that now pins Rust nightly-2024-05-01. This commit updates CI to match.

ci: update cargo-check-external-types toolchain

---

src/alg_tests.rs
src/cert.rs
src/crl/mod.rs
src/crl/types.rs
src/der.rs
src/end_entity.rs
src/error.rs
src/lib.rs
src/signed_data.rs
src/subject_name/dns_name.rs
src/subject_name/ip_address.rs
src/subject_name/verify.rs
src/time.rs
src/trust_anchor.rs
src/verify_cert.rs
src/x509.rs

Triggered by some confusion while looking at https://github.com/rustls/rustls/pull/1954 and getting confused by the lack of lifetimes on `SubjectKeyInfoDer` return values.

Enable some more warnings on lints

---

src/crl/types.rs
src/error.rs
src/lib.rs
src/verify_cert.rs
src/x509.rs

This was accidentally added to the `allow` lints instead of the `warn` lints in https://github.com/rustls/webpki/pull/262.

lib: warn for clippy::use_self

---

Cargo.lock
Cargo.toml

* `EndEntityCert::subject_public_key_info()` as added in [0.102.4](https://github.com/rustls/webpki/releases/tag/v%2F0.102.4) neglected to specify the return type's lifetime, limiting the visible lifetime to the lifetime of the `EndEntityCert`. The actual lifetime was `'static`; we've made this explicit and enabled warnings for `elided_lifetimes_in_paths` to avoid similar issues in the future.
To support https://github.com/rustls/rustls/pull/1954#discussion_r1660219420.

Prepare 0.102.5 release

---

src/crl/types.rs

Nightly rustdoc flags these as non-standard markdown, and they don't render as nicely as just using a link. See also https://github.com/rustls/rustls/pull/2033
Fixes [build errors on main](https://github.com/rustls/webpki/actions/runs/9821191816/job/27116602046).

types: avoid markdown footnotes

---

deny.toml

cargo-deny got updated and changed some configuration stuff:
```
djc-2021 main webpki $ cargo deny check licenses
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
┌─ /Users/djc/src/webpki/deny.toml:2:1
│
2 │ unmaintained = "deny"
│ ━━━━━━━━━━━━
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
┌─ /Users/djc/src/webpki/deny.toml:4:1
│
4 │ notice = "deny"
│ ━━━━━━
2024-08-03 15:03:31 [ERROR] failed to validate configuration file /Users/djc/src/webpki/deny.toml
```

Update deny config

---

Cargo.lock
Cargo.toml
src/alg_tests.rs
src/aws_lc_rs_algs.rs
src/ring_algs.rs
third-party/chromium/data/verify_signed_data/ours/ecdsa-prime256v1-sha256-compressed.pem
third-party/chromium/data/verify_signed_data/ours/ecdsa-prime256v1-sha256-spki-inside-spki.pem
third-party/chromium/data/verify_signed_data/ours/ecdsa-prime256v1-sha256.pem

Proposed release notes:
- **Support for aws-lc-rs 1.9 added**. This release adds supports for compressed EC public keys, when used with aws-lc-rs.
(nb. I plan to enable the `prebuilt-nasm` feature at the rustls level, not here. Mainly because this crate has a slower release cadence and it seems like a good idea to make that decision as high in the stack as possible.)

Take aws-lc-rs 1.9

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/lib.rs

Replaces #293. See:
* https://github.com/rustls/rustls/pull/2220

Update dependencies & bump MSRV to 1.71

---

benches/benchmark.rs
src/crl/mod.rs
src/crl/types.rs
src/der.rs
src/end_entity.rs
src/rpk_entity.rs
src/verify_cert.rs
src/x509.rs

Applies `clippy --fix` to remove findings [presently breaking the `clippy` task](https://github.com/rustls/webpki/actions/runs/12073854466/job/33670784016) as of 1.83 being released.

proj: fix clippy 1.83 findings

---

.github/workflows/testgen.yml

We were consistent about doing this in the main CI workflow, but not the testgen workflow. This [is flagged](https://woodruffw.github.io/zizmor/audits/#artipacked) when running Zizmor 0.7.0 on the repo's CI config. As mentioned in the description of this finding:
> By default, using [actions/checkout](https://github.com/actions/checkout) causes a credential to be persisted in the checked-out repo's .git/config, so that subsequent git operations can be authenticated.
>
> Subsequent steps may accidentally publicly persist .git/config, e.g. by including it in a publicly accessible artifact via [actions/upload-artifact](https://github.com/actions/upload-artifact).
>
> However, even without this, persisting the credential in the .git/config is non-ideal unless actually needed.
We don't need …

ci: use persist-credentials: false in testgen.yml

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/lib.rs
src/verify_cert.rs
tests/better_tls.rs
tests/client_auth.rs
tests/client_auth_revocation.rs
tests/custom_ekus.rs
tests/generate.py
tests/integration.rs
tests/signatures.rs
tests/tls_server_certs.rs

Previously we unconditionally used the `aws-lc-sys` and `prebuilt-nasm` features of the `aws-lc-rs` dep, meaning we always brought along `aws-lc-sys` (note the `prebuilt-nasm` feature customizes that dep).
However, when a user is looking for a FIPS crypto provider we want to avoid bringing in `aws-lc-sys` and instead use `aws-lc-rs/fips` to get `aws-lc-fips-sys`.
This commit makes the `aws-lc-rs` feature of `webpki` activate the "usual" config: `aws-lc-rs/aws-lc-sys` w/ `aws-lc-rs/prebuilt-nasm` to have `aws-lc-sys` with prebuilt assmebly to avoid the nasm dep.
A new `aws-lc-rs-fips` feature is added for `webpki` that activates the FIPS specific config: `aws-lc-rs/fips`. The `aws-lc-sys` and `prebuilt-nasm` features are **not** activated.
Updates …

add aws-lc-rs-fips feature, adjust sys dep

---

src/der.rs
src/end_entity.rs
src/error.rs
src/lib.rs
src/subject_name/dns_name.rs
src/subject_name/ip_address.rs
src/subject_name/verify.rs
tests/custom_ekus.rs
tests/generate.py
tests/tls_server_certs.rs

This pretty much achieves my goals and is probably workable but not quite pretty:
- No `Copy` for `Error` means a semver-incompatible change
* Semver-incompatible changes in webpki specifically are relatively manageable since most users don't depend on it directly
- A little strange to get different errors for `alloc` vs no `alloc`?
I can fix test failures etc if we think this is worth doing.

Add context in name validation errors

---

src/lib.rs
tests/better_tls.rs

Mentioned as a 0.103 candidate in https://github.com/rustls/pki-types/pull/24#issuecomment-1846847853

Remove re-export of rustls-pki-types

---

Cargo.lock
deny.toml

Updating ring v0.17.8 -> v0.17.13
Also a few small `cargo deny` fixes:
* deny: remove LicenseRef-ring: This license is no longer being encountered by `cargo deny` after `*ring*` 0.17.10 incorporated the upstream BoringSSL relicense work.
* deny: ignore [RUSTSEC-2024-0436](https://rustsec.org/advisories/RUSTSEC-2024-0436) - we'll follow the upstream progress on this one.

Cargo: ring 0.17.8 -> 0.17.13

---

Cargo.lock
Cargo.toml
src/der.rs

* Avoid a possible type inference error when building in projects that also use `jhpratt/deranged`.
Resolves https://github.com/rustls/webpki/issues/333

avoid inference hazard usize comparison

---

Cargo.toml

Hi everyone 👋
While reviewing dependency updates in our project (trying to assure supply chain safety) I noticed that the `tests` directory contains many binary files and a couple of scripts as well. That makes it harder to review when checking the supply chain and I was wondering if it would be possible to remove this directory from the published package. That would remove a potential vector for a security vulnerability in the future.
The downside of course would be that the tests couldn't be run from the crate package anymore, but I'm not sure how popular that is.
Best regards!

Remove tests from package that is published

---

Cargo.lock
Cargo.toml

Add support for RSA signature algorithms that don't include parameters. Per [RFC 4055 section 5](https://www.rfc-editor.org/rfc/rfc4055#section-5), implementations of the SHA-1/SHA-2 one-way hash functions "MUST accept the parameters being absent as well as present".

Bump version to 0.103.3

---

Cargo.toml

Currently, all `README.md` files in the crate are included when publishing, which includes `third-party/bettertls/README.md`. This looks unintentional. Using an absolute path in the `package.include` setting instead (i.e. `/README.md`) causes only the toplevel README file to get included.

Do not include bettertls README file in published crates

---

Cargo.lock

the 1.13.1 version has a fix for `*-pc-windows-gnullvm` target: https://github.com/aws/aws-lc/pull/2381/

deps: Update aws-lc-rs in lockfile

---

Cargo.lock
Cargo.toml
src/lib.rs

Draft state to prevent merging before downstream is ready -- please review.
* Add unstable support for the post-quantum ML-DSA signature algorithms when using aws-lc-rs. Enable the `aws-lc-rs-unstable` feature to expose these algorithms (only works when `aws-lc-rs-fips` is not enabled).
* Use new `UnsupportedSignatureAlgorithmContext`, `UnsupportedCrlSignatureAlgorithmContext`, `UnsupportedSignatureAlgorithmForPublicKeyContext` and `UnsupportedCrlSignatureAlgorithmForPublicKeyContext` error variants which contain additional context about the error condition. The related contextless variants have been deprecated.

Bump version to 0.103.4

---

src/lib.rs
src/verify_cert.rs

Export more types to enable ExtendedKeyUsageValidator implementations
